// frontend/admin-vue/src/FeederAudit.vue
<script setup>
import { ref, onMounted } from 'vue';
import { baseUrl } from '../config';
import { ElMessageBox } from 'element-plus';
const feeders = ref([]);
const fetchFeeders = async () => {
  const res = await fetch(baseUrl + '/admin/feeders');
  const json = await res.json();
  feeders.value = json.data || [];
};
const audit = async (id, approve) => {
  await fetch(baseUrl + '/admin/feeders/audit', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ feederId: id, approve }),
  });
  fetchFeeders();
};
onMounted(fetchFeeders);
</script>
<template>
  <el-table :data="feeders" style="width: 100%">
    <el-table-column prop="name" label="Name" />
    <el-table-column prop="phone" label="Phone" />
    <el-table-column>
      <template #default="{ row }">
        <el-button type="success" @click="audit(row.id, true)">Approve</el-button>
        <el-button type="danger" @click="audit(row.id, false)">Reject</el-button>
      </template>
    </el-table-column>
  </el-table>
</template>

// frontend/admin/src/FeederAudit.jsx
import React, { useEffect, useState } from 'react';
import { baseUrl } from '../config';

export default function FeederAudit() {
  const [feeders, setFeeders] = useState([]);

  useEffect(() => {
    fetch(baseUrl + '/feeders')
      .then((r) => r.json())
      .then((d) => setFeeders(d.data || []));
  }, []);

  const updateStatus = (id, status) => {
    fetch(`${baseUrl}/feeders/${id}/status/${status}`, { method: 'PATCH' })
      .then(() => setFeeders((prev) => prev.filter((f) => f.id !== id)));
  };

  return (
    <div>
      <h2>Feeder Audit</h2>
      <ul>
        {feeders.map((f) => (
          <li key={f.id}>
            {f.name} - {f.phone}
            <button onClick={() => updateStatus(f.id, 1)}>Approve</button>
            <button onClick={() => updateStatus(f.id, 2)}>Reject</button>
          </li>
        ))}
      </ul>
    </div>
  );
}
