// frontend/admin/src/OrderList.jsx
import React, { useEffect, useState } from 'react';
import { baseUrl } from '../config';

export default function OrderList() {
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    fetch(baseUrl + '/service-orders')
      .then((r) => r.json())
      .then((d) => setOrders(d.data || []));
  }, []);

  return (
    <div>
      <h2>Service Orders</h2>
      <ul>
        {orders.map((o) => (
          <li key={o.id}>
            Order #{o.id} - {o.status}
            {o.completeImages && o.completeImages.map((img) => (
              <img key={img} src={img} alt="" width="60" />
            ))}
          </li>
        ))}
      </ul>
    </div>
  );
}

// frontend/admin-vue/src/OrderList.vue
<script setup>
import { ref, onMounted } from 'vue';
import { baseUrl } from '../config';

const orders = ref([]);
const fetchOrders = async () => {
  const res = await fetch(baseUrl + '/service-orders');
  const json = await res.json();
  orders.value = json.data || [];
};

onMounted(fetchOrders);
</script>
<template>
  <n-table :bordered="false" :single-line="false">
    <thead>
      <tr>
        <th>ID</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="order in orders" :key="order.id">
        <td>{{ order.id }}</td>
        <td>{{ order.status }}</td>
      </tr>
    </tbody>
  </n-table>
</template>
